### ISSUE TITLE
Enquiry about Some Code for Reproducibility

### ISSUE THREAD

**Issue by zhiheLu** [threedle/3DHighlighter#2]
Thanks for your great work. We have met each other on CVPR this year.

I am interested in this work and hope you could release some code for reproducing the results in the paper.

1. The code for computing CLIP R-Precision. BTW, which object is selected for evaluation?
2. The demo code is customized to given objects only. Could you please provide the code for running other datasets, e.g., ".off" file in COSEG dataset?

Many thanks. I am looking forward to your reply.

**Comment by ddecatur** [comment]
Hello. For 1) I just emailed you the data and code required to reproduce the CLIP R-Precision table from the paper. For 2) the code currently only supports meshes in the ".obj" format. Since COSEG has meshes in the ".off" format, I used [MeshLab](https://www.meshlab.net/) to convert them from ".off" format to ".obj" format.
